baseurl         = "https://djidjoudemasse.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Ramsès Djidjou-Demasse"
  subtitle    = "Dynamical Systems, Population Biology of Infectious Diseases"

  cover       = "img/blog-cover.jpg"
  description = "IRD Researcher. I focus on population dynamics, usually of host-natural enemy interactions, to understand fundamental processes in epidemiology, ecology and evolution of infectious disease. My works are based on a combination of Mathematical analysis and Modeling with a particular focus on Dynamical Systems."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = "logo_IRD.png"
  orgName = "IRD"
  orgWebsite = "https://en.ird.fr/"
  orgDescription = "The French National Research Institute for Development (IRD) is an internationally multidisciplinary organisation working primarily in partnership with Mediterranean and intertropical countries."

  author = "RDD"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Montpellier, FR"
  authorWebsite = "https://djidjoudemasse.com"
  authorDescription = "IRD Researcher. I focus on population dynamics, usually of host-natural enemy interactions, to understand fundamental processes in epidemiology, ecology and evolution of infectious disease. My works are based on a combination of Mathematical analysis and Modeling with a particular focus on Dynamical Systems."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/:slug/"


[[menu.main]]
  name = "HOME"
  url = "/"
  weight = 300



[[menu.main]]
  name = "PUBLICATIONS"
  url = "https://cv.archives-ouvertes.fr/ramses-djidjou-demasse#"
  weight = 230

#[[menu.main]]
#  name = "NEWS"
#  url = "/tags/news/"
#  weight = 200

[[menu.main]]
  name = "OPPORTUNITIES"
  url = "/tags/opportunities/"
  weight = 200

#[[menu.main]]
#  name = "CONTACT"
#  url = "/categories/contact/"
#  weight = 100

#[[menu.main]]
  #name = "Go"
  #url = "/tags/golang/"
  #weight = 100

#[[menu.main]]
  #name = "Food"
  #url = "/categories/food/"
  #weight = 99

#[[menu.main]]
  #name = "Google"
  #url = "https://google.com/"
  #weight = 95
