baseurl         = "https://djidjoudemasse.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Rams Djidjou-Demasse"
  subtitle    = "under construction"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = ""#"hugo-logo.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "RDD"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Montpellier, FR"
  authorWebsite = "https://djidjoudemasse.com"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/:slug/"


[[menu.main]]
  name = "HOME"
  url = "/"
  weight = 300


[[menu.main]]
  name = "RESEARCH"
  url = "/tags/research/"
  weight = 200

[[menu.main]]
  name = "PUBLICATIONS"
  url = "/categories/publications/"
  weight = 200

[[menu.main]]
  name = "NEWS"
  url = "/tags/news/"
  weight = 200

[[menu.main]]
  name = "OPPORTUNITIES"
  url = "/tags/opportunities/"
  weight = 200

[[menu.main]]
  name = "CONTACT"
  url = "/categories/contact/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Food"
  url = "/categories/food/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95
